# Generated by Django 6.0.3 on 2026-03-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.IntegerField(choices=[(7, '7%'), (8, '8%'), (9, '9%')])),
                ('porcentaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_trabajador', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_reinversion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ampliacion_prestamo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('abonos_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('realizado', models.BooleanField(default=False)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
            ],
        ),
    ]
