# Generated by Django 6.0.3 on 2026-03-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='monto_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='monto_gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='monto_reinversion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='monto_trabajador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
