# Generated by Django 6.0.3 on 2026-03-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_monto_ganancia_cliente_monto_gastos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='abonos_capital',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ampliacion_prestamo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='monto_ganancia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='monto_gastos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='monto_reinversion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='monto_trabajador',
        ),
    ]
