# Generated by Django 6.0.3 on 2026-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_abonos_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
